config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users
  resource :session
  namespace :api, defaults: {format: :json} do
    resources :bills, except: [:new, :edit] do
      post 'mail_to_people'
    end
    resources :roommates, only: [:create, :update, :destroy]
    resources :follows, only: [:update, :destroy, :show]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, presence: true
  validates :password, length: { minimum: 5, allow_nil: true }
  validates :email, uniqueness: true

  has_many(
    :bills,
    class_name: "Bill",
    primary_key: :id,
    foreign_key: :owner_id
  )

  has_many(
    :taggings,
    class_name: "Follow",
    primary_key: :id,
    foreign_key: :user_id
  )

  has_many(
    :tagged_bills,
    through: :taggings,
    source: :bill,

  )

  has_many :comments

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  protected

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

 def create
   @user = User.new(user_params)

   if @user.save
     sign_in!(@user)
     redirect_to root_url
   else
     flash.now[:errors] = @user.errors.full_messages
     render :new
   end
 end

 private

 def user_params
   params.require(:user).permit(:email, :password)
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="landingEntry">
    <div class="logo group">
      <img class="main_title" src="http://res.cloudinary.com/bill-organizer/image/upload/c_scale,h_201/v1438989682/Bill_Organizer-logo_qeau8i.png"></img>
    </div>

    <div class="sign_in">
    <h1>Sign Up</h1>

    <form action="/users" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <label>Email<br>
        <input name="user[email]" type="text"><br>
      </label><br><br>
      <label>Password<br>
        <input name="user[password]" type="password"><br>
      </label><br><br>
      <input type="submit" value="Submit" class="btn btn-primary"><br>
    </form>
    <br>
    <div>Sign in <a href="<%=new_session_url%>">here</a></div>
    </div>
</div>